server:
  addr : 0.0.0.0
  port: 8081
  # silent debug info warn error
  gorm_log_level: debug
  # debug info warn error
  profile: test
  configPath: .\configs
  logPath: .\log
  logName:  test
swagger:
  enable: true
pprof:
  enable: true