server:
  addr : 0.0.0.0
  port: 8081
  # silent debug info warn error
  gorm_log_level: debug
  # debug info warn error
  zap_log_level: debug
  profile: dev
  configPath: ./configs
  logPath: ./log
  logName:  test
  simple_stdout: false
  function_name: true
swagger:
  enable: true
pprof:
  enable: true
feiShu:
  enable: false
  url: "url"
  group_id: "group_id"
