server:
  addr : 0.0.0.0
  port: 8081
  # debug info warn error
  loglevel: debug
  profile: test
  configPath: .\configs
  logPath: .\log
  logName:  test
swagger:
  enable: true
pprof:
  enable: true