// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.25.3
// source: dispatch_enum.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Grp int32

const (
	Grp_Def   Grp = 0
	Grp_Sys   Grp = 1
	Grp_Logic Grp = 2
)

// Enum value maps for Grp.
var (
	Grp_name = map[int32]string{
		0: "Def",
		1: "Sys",
		2: "Logic",
	}
	Grp_value = map[string]int32{
		"Def":   0,
		"Sys":   1,
		"Logic": 2,
	}
)

func (x Grp) Enum() *Grp {
	p := new(Grp)
	*p = x
	return p
}

func (x Grp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Grp) Descriptor() protoreflect.EnumDescriptor {
	return file_dispatch_enum_proto_enumTypes[0].Descriptor()
}

func (Grp) Type() protoreflect.EnumType {
	return &file_dispatch_enum_proto_enumTypes[0]
}

func (x Grp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Grp.Descriptor instead.
func (Grp) EnumDescriptor() ([]byte, []int) {
	return file_dispatch_enum_proto_rawDescGZIP(), []int{0}
}

type Cmd_Sys int32

const (
	Cmd_Sys_Def_Cmd_Sys           Cmd_Sys = 0
	Cmd_Sys_Subscribe_Online_User Cmd_Sys = 1
	Cmd_Sys_Kick_Online_User      Cmd_Sys = 2
	Cmd_Sys_Push_Message          Cmd_Sys = 3
)

// Enum value maps for Cmd_Sys.
var (
	Cmd_Sys_name = map[int32]string{
		0: "Def_Cmd_Sys",
		1: "Subscribe_Online_User",
		2: "Kick_Online_User",
		3: "Push_Message",
	}
	Cmd_Sys_value = map[string]int32{
		"Def_Cmd_Sys":           0,
		"Subscribe_Online_User": 1,
		"Kick_Online_User":      2,
		"Push_Message":          3,
	}
)

func (x Cmd_Sys) Enum() *Cmd_Sys {
	p := new(Cmd_Sys)
	*p = x
	return p
}

func (x Cmd_Sys) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cmd_Sys) Descriptor() protoreflect.EnumDescriptor {
	return file_dispatch_enum_proto_enumTypes[1].Descriptor()
}

func (Cmd_Sys) Type() protoreflect.EnumType {
	return &file_dispatch_enum_proto_enumTypes[1]
}

func (x Cmd_Sys) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cmd_Sys.Descriptor instead.
func (Cmd_Sys) EnumDescriptor() ([]byte, []int) {
	return file_dispatch_enum_proto_rawDescGZIP(), []int{1}
}

type Cmd_Logic int32

const (
	Cmd_Logic_Def_Cmd_Logic Cmd_Logic = 0
	Cmd_Logic_Health        Cmd_Logic = 1
)

// Enum value maps for Cmd_Logic.
var (
	Cmd_Logic_name = map[int32]string{
		0: "Def_Cmd_Logic",
		1: "Health",
	}
	Cmd_Logic_value = map[string]int32{
		"Def_Cmd_Logic": 0,
		"Health":        1,
	}
)

func (x Cmd_Logic) Enum() *Cmd_Logic {
	p := new(Cmd_Logic)
	*p = x
	return p
}

func (x Cmd_Logic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cmd_Logic) Descriptor() protoreflect.EnumDescriptor {
	return file_dispatch_enum_proto_enumTypes[2].Descriptor()
}

func (Cmd_Logic) Type() protoreflect.EnumType {
	return &file_dispatch_enum_proto_enumTypes[2]
}

func (x Cmd_Logic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cmd_Logic.Descriptor instead.
func (Cmd_Logic) EnumDescriptor() ([]byte, []int) {
	return file_dispatch_enum_proto_rawDescGZIP(), []int{2}
}

var File_dispatch_enum_proto protoreflect.FileDescriptor

var file_dispatch_enum_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x2a, 0x22, 0x0a, 0x03, 0x47, 0x72, 0x70,
	0x12, 0x07, 0x0a, 0x03, 0x44, 0x65, 0x66, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x79, 0x73,
	0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x10, 0x02, 0x2a, 0x5d, 0x0a,
	0x07, 0x43, 0x6d, 0x64, 0x5f, 0x53, 0x79, 0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x65, 0x66, 0x5f,
	0x43, 0x6d, 0x64, 0x5f, 0x53, 0x79, 0x73, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x5f, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x55, 0x73,
	0x65, 0x72, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4b, 0x69, 0x63, 0x6b, 0x5f, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x75,
	0x73, 0x68, 0x5f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x03, 0x2a, 0x2a, 0x0a, 0x09,
	0x43, 0x6d, 0x64, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x65, 0x66,
	0x5f, 0x43, 0x6d, 0x64, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x10, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dispatch_enum_proto_rawDescOnce sync.Once
	file_dispatch_enum_proto_rawDescData = file_dispatch_enum_proto_rawDesc
)

func file_dispatch_enum_proto_rawDescGZIP() []byte {
	file_dispatch_enum_proto_rawDescOnce.Do(func() {
		file_dispatch_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_dispatch_enum_proto_rawDescData)
	})
	return file_dispatch_enum_proto_rawDescData
}

var file_dispatch_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_dispatch_enum_proto_goTypes = []interface{}{
	(Grp)(0),       // 0: pb.Grp
	(Cmd_Sys)(0),   // 1: pb.Cmd_Sys
	(Cmd_Logic)(0), // 2: pb.Cmd_Logic
}
var file_dispatch_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dispatch_enum_proto_init() }
func file_dispatch_enum_proto_init() {
	if File_dispatch_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dispatch_enum_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dispatch_enum_proto_goTypes,
		DependencyIndexes: file_dispatch_enum_proto_depIdxs,
		EnumInfos:         file_dispatch_enum_proto_enumTypes,
	}.Build()
	File_dispatch_enum_proto = out.File
	file_dispatch_enum_proto_rawDesc = nil
	file_dispatch_enum_proto_goTypes = nil
	file_dispatch_enum_proto_depIdxs = nil
}
