// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: dispatch_enum.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Grp int32

const (
	Grp_Def     Grp = 0
	Grp_Sys     Grp = 1
	Grp_Public  Grp = 2
	Grp_Private Grp = 3
)

// Enum value maps for Grp.
var (
	Grp_name = map[int32]string{
		0: "Def",
		1: "Sys",
		2: "Public",
		3: "Private",
	}
	Grp_value = map[string]int32{
		"Def":     0,
		"Sys":     1,
		"Public":  2,
		"Private": 3,
	}
)

func (x Grp) Enum() *Grp {
	p := new(Grp)
	*p = x
	return p
}

func (x Grp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Grp) Descriptor() protoreflect.EnumDescriptor {
	return file_dispatch_enum_proto_enumTypes[0].Descriptor()
}

func (Grp) Type() protoreflect.EnumType {
	return &file_dispatch_enum_proto_enumTypes[0]
}

func (x Grp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Grp.Descriptor instead.
func (Grp) EnumDescriptor() ([]byte, []int) {
	return file_dispatch_enum_proto_rawDescGZIP(), []int{0}
}

type CmdSys int32

const (
	CmdSys_DefCmdSys      CmdSys = 0
	CmdSys_KickOnlineUser CmdSys = 1
)

// Enum value maps for CmdSys.
var (
	CmdSys_name = map[int32]string{
		0: "DefCmdSys",
		1: "KickOnlineUser",
	}
	CmdSys_value = map[string]int32{
		"DefCmdSys":      0,
		"KickOnlineUser": 1,
	}
)

func (x CmdSys) Enum() *CmdSys {
	p := new(CmdSys)
	*p = x
	return p
}

func (x CmdSys) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdSys) Descriptor() protoreflect.EnumDescriptor {
	return file_dispatch_enum_proto_enumTypes[1].Descriptor()
}

func (CmdSys) Type() protoreflect.EnumType {
	return &file_dispatch_enum_proto_enumTypes[1]
}

func (x CmdSys) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdSys.Descriptor instead.
func (CmdSys) EnumDescriptor() ([]byte, []int) {
	return file_dispatch_enum_proto_rawDescGZIP(), []int{1}
}

type CmdPublic int32

const (
	CmdPublic_DefCmdPublic    CmdPublic = 0
	CmdPublic_HealthCheck     CmdPublic = 1
	CmdPublic_TickerSubscribe CmdPublic = 2
)

// Enum value maps for CmdPublic.
var (
	CmdPublic_name = map[int32]string{
		0: "DefCmdPublic",
		1: "HealthCheck",
		2: "TickerSubscribe",
	}
	CmdPublic_value = map[string]int32{
		"DefCmdPublic":    0,
		"HealthCheck":     1,
		"TickerSubscribe": 2,
	}
)

func (x CmdPublic) Enum() *CmdPublic {
	p := new(CmdPublic)
	*p = x
	return p
}

func (x CmdPublic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdPublic) Descriptor() protoreflect.EnumDescriptor {
	return file_dispatch_enum_proto_enumTypes[2].Descriptor()
}

func (CmdPublic) Type() protoreflect.EnumType {
	return &file_dispatch_enum_proto_enumTypes[2]
}

func (x CmdPublic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdPublic.Descriptor instead.
func (CmdPublic) EnumDescriptor() ([]byte, []int) {
	return file_dispatch_enum_proto_rawDescGZIP(), []int{2}
}

type CmdPrivate int32

const (
	CmdPrivate_DefCmdPrivate CmdPrivate = 0
	CmdPrivate_Health        CmdPrivate = 1
)

// Enum value maps for CmdPrivate.
var (
	CmdPrivate_name = map[int32]string{
		0: "DefCmdPrivate",
		1: "Health",
	}
	CmdPrivate_value = map[string]int32{
		"DefCmdPrivate": 0,
		"Health":        1,
	}
)

func (x CmdPrivate) Enum() *CmdPrivate {
	p := new(CmdPrivate)
	*p = x
	return p
}

func (x CmdPrivate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdPrivate) Descriptor() protoreflect.EnumDescriptor {
	return file_dispatch_enum_proto_enumTypes[3].Descriptor()
}

func (CmdPrivate) Type() protoreflect.EnumType {
	return &file_dispatch_enum_proto_enumTypes[3]
}

func (x CmdPrivate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdPrivate.Descriptor instead.
func (CmdPrivate) EnumDescriptor() ([]byte, []int) {
	return file_dispatch_enum_proto_rawDescGZIP(), []int{3}
}

type TypeKickReason int32

const (
	TypeKickReason_DefKickReason TypeKickReason = 0
	// 只能一个端登录
	TypeKickReason_OnlyOneClient TypeKickReason = 1
)

// Enum value maps for TypeKickReason.
var (
	TypeKickReason_name = map[int32]string{
		0: "DefKickReason",
		1: "OnlyOneClient",
	}
	TypeKickReason_value = map[string]int32{
		"DefKickReason": 0,
		"OnlyOneClient": 1,
	}
)

func (x TypeKickReason) Enum() *TypeKickReason {
	p := new(TypeKickReason)
	*p = x
	return p
}

func (x TypeKickReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeKickReason) Descriptor() protoreflect.EnumDescriptor {
	return file_dispatch_enum_proto_enumTypes[4].Descriptor()
}

func (TypeKickReason) Type() protoreflect.EnumType {
	return &file_dispatch_enum_proto_enumTypes[4]
}

func (x TypeKickReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeKickReason.Descriptor instead.
func (TypeKickReason) EnumDescriptor() ([]byte, []int) {
	return file_dispatch_enum_proto_rawDescGZIP(), []int{4}
}

type TypeTickerSubscribe int32

const (
	TypeTickerSubscribe_DefTickerSubscribe TypeTickerSubscribe = 0
	TypeTickerSubscribe_Test               TypeTickerSubscribe = 1
)

// Enum value maps for TypeTickerSubscribe.
var (
	TypeTickerSubscribe_name = map[int32]string{
		0: "DefTickerSubscribe",
		1: "Test",
	}
	TypeTickerSubscribe_value = map[string]int32{
		"DefTickerSubscribe": 0,
		"Test":               1,
	}
)

func (x TypeTickerSubscribe) Enum() *TypeTickerSubscribe {
	p := new(TypeTickerSubscribe)
	*p = x
	return p
}

func (x TypeTickerSubscribe) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeTickerSubscribe) Descriptor() protoreflect.EnumDescriptor {
	return file_dispatch_enum_proto_enumTypes[5].Descriptor()
}

func (TypeTickerSubscribe) Type() protoreflect.EnumType {
	return &file_dispatch_enum_proto_enumTypes[5]
}

func (x TypeTickerSubscribe) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeTickerSubscribe.Descriptor instead.
func (TypeTickerSubscribe) EnumDescriptor() ([]byte, []int) {
	return file_dispatch_enum_proto_rawDescGZIP(), []int{5}
}

var File_dispatch_enum_proto protoreflect.FileDescriptor

var file_dispatch_enum_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x2a, 0x30, 0x0a, 0x03, 0x47, 0x72, 0x70,
	0x12, 0x07, 0x0a, 0x03, 0x44, 0x65, 0x66, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x79, 0x73,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x10, 0x03, 0x2a, 0x2b, 0x0a, 0x06, 0x43,
	0x6d, 0x64, 0x53, 0x79, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x65, 0x66, 0x43, 0x6d, 0x64, 0x53,
	0x79, 0x73, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x10, 0x01, 0x2a, 0x43, 0x0a, 0x09, 0x43, 0x6d, 0x64, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x65, 0x66, 0x43, 0x6d, 0x64, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x72, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x10, 0x02, 0x2a, 0x2b, 0x0a,
	0x0a, 0x43, 0x6d, 0x64, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x44,
	0x65, 0x66, 0x43, 0x6d, 0x64, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x10, 0x01, 0x2a, 0x36, 0x0a, 0x0e, 0x54, 0x79,
	0x70, 0x65, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x11, 0x0a, 0x0d,
	0x44, 0x65, 0x66, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x10, 0x00, 0x12,
	0x11, 0x0a, 0x0d, 0x4f, 0x6e, 0x6c, 0x79, 0x4f, 0x6e, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x10, 0x01, 0x2a, 0x37, 0x0a, 0x13, 0x54, 0x79, 0x70, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x44, 0x65, 0x66,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x10, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dispatch_enum_proto_rawDescOnce sync.Once
	file_dispatch_enum_proto_rawDescData = file_dispatch_enum_proto_rawDesc
)

func file_dispatch_enum_proto_rawDescGZIP() []byte {
	file_dispatch_enum_proto_rawDescOnce.Do(func() {
		file_dispatch_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_dispatch_enum_proto_rawDescData)
	})
	return file_dispatch_enum_proto_rawDescData
}

var file_dispatch_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_dispatch_enum_proto_goTypes = []any{
	(Grp)(0),                 // 0: pb.Grp
	(CmdSys)(0),              // 1: pb.CmdSys
	(CmdPublic)(0),           // 2: pb.CmdPublic
	(CmdPrivate)(0),          // 3: pb.CmdPrivate
	(TypeKickReason)(0),      // 4: pb.TypeKickReason
	(TypeTickerSubscribe)(0), // 5: pb.TypeTickerSubscribe
}
var file_dispatch_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dispatch_enum_proto_init() }
func file_dispatch_enum_proto_init() {
	if File_dispatch_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dispatch_enum_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dispatch_enum_proto_goTypes,
		DependencyIndexes: file_dispatch_enum_proto_depIdxs,
		EnumInfos:         file_dispatch_enum_proto_enumTypes,
	}.Build()
	File_dispatch_enum_proto = out.File
	file_dispatch_enum_proto_rawDesc = nil
	file_dispatch_enum_proto_goTypes = nil
	file_dispatch_enum_proto_depIdxs = nil
}
