dataSource:
  - addr: 127.0.0.1
    port: 55002
    username: root
    password: admin123
    idle_conn: 10
    max_conn: 20
    max_idle_time: 20
    max_life_time: 20
    charset: utf8mb4
    db_name: test
    name: test
    type: mysql
    slow_sql: 100 #ms
jwt:
  secret: 12345678
  expire: 30 #day
ws:
  multiLoginPolicy: 1