// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/user/create": {
            "post": {
                "description": "User创建",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "创建接口",
                "parameters": [
                    {
                        "description": "User创建请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User创建返回结果",
                        "schema": {
                            "$ref": "#/definitions/response.UserCreate"
                        }
                    }
                }
            }
        },
        "/v1/user/delete": {
            "post": {
                "description": "User删除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "删除接口",
                "parameters": [
                    {
                        "description": "User删除请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User删除返回结果",
                        "schema": {
                            "$ref": "#/definitions/response.UserDelete"
                        }
                    }
                }
            }
        },
        "/v1/user/list": {
            "post": {
                "description": "User列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "列表接口",
                "parameters": [
                    {
                        "description": "User列表请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User列表返回结果",
                        "schema": {
                            "$ref": "#/definitions/response.UserList"
                        }
                    }
                }
            }
        },
        "/v1/user/update": {
            "post": {
                "description": "User更新",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "更新接口",
                "parameters": [
                    {
                        "description": "User更新请求参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User更新返回结果",
                        "schema": {
                            "$ref": "#/definitions/response.UserUpdate"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.UserCreate": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "年龄",
                    "type": "integer"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                }
            }
        },
        "request.UserDelete": {
            "type": "object",
            "properties": {
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "request.UserList": {
            "type": "object",
            "required": [
                "current_page",
                "page_count"
            ],
            "properties": {
                "current_page": {
                    "type": "integer",
                    "minimum": 1
                },
                "page_count": {
                    "type": "integer",
                    "maximum": 50
                }
            }
        },
        "request.UserUpdate": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "年龄",
                    "type": "integer"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "response.User": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "年龄",
                    "type": "integer"
                },
                "created_time": {
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "response.UserCreate": {
            "type": "object"
        },
        "response.UserDelete": {
            "type": "object"
        },
        "response.UserList": {
            "type": "object",
            "properties": {
                "user_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.User"
                    }
                }
            }
        },
        "response.UserUpdate": {
            "type": "object"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"http"},
	Title:            "framework API Document",
	Description:      "framework API Document",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
